#! /bin/sh

### BEGIN INIT INFO
# Provides:          videochat
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: videochat
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting videochat"
    node /usr/local/videochat/server/server.js > /var/log/videochat.log 2>&1 &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping videochat"

    kill `ps ax | grep server.js | grep node | awk '{print $1}'` > /dev/null

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/videochat {start|stop}"
    exit 1
    ;;
esac
